name: pull-request-opened

on:
  pull_request:
    types: [opened]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.8
      - name: Install Dependencies
        run: go get .
      - name: Remove Unused Modules
        run: go mod tidy

  lint:
    needs:
      - install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Golang CI Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  
  test:
    needs:
      - install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: unit tests
        run: go test ./...